[build]
  # Since this is a static HTML site, no build command is needed
  publish = "."

[build.environment]
  # No environment variables needed for static HTML

[[headers]]
  # Apply security headers to all pages
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Redirect all 404s to index.html for single page behavior
  from = "/*"
  to = "/index.html"
  status = 200
